#pragma once

typedef struct _S_PT_CHANNEL_ENTER
{
	WCHAR USER_ID[32];
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
} S_PT_CHANNEL_ENTER;

typedef struct _S_PT_CHANNEL_ENTER_SUCC_U
{
	DOWRD_PTR SESSION_ID;
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
	WCHAR REAL_ADDRESS[32];
	USHORT REAL_PORT;
} S_PT_CHANNEL_ENTER_SUCC_U;

typedef struct _S_PT_CHANNEL_ENTER_FAIL_U
{
	DWORD ERRROR_CODE;
} S_PT_CHANNEL_ENTER_FAIL_U;

typedef struct _S_PT_ROOM_ENTER_M
{
	DWORD SLOT_POSITION;
	WCHAR USER_ID[32];
	DWORD_PTR SESSION_ID;
	DWORD VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
	WCHAR REAL_ADDRESS[32];
	USHORT REAL_PORT;
} S_PT_ROOM_ENTER_M;

typedef struct _S_PT_ROOM_REQ_INFO
{
} S_PT_ROOM_REQ_INFO;

typedef struct _S_PT_ROOM_REQ_INFO_SUCC_U
{
	DWORD ROOM_INDEX;
	WCHAR TITLE[32];
	DWORD MAP_INDEX;
	USHORT CURRENT_USER_COUNT;
	DWORD_PTR ROOT_USER_SESSION_ID;
	SLOT_USER_DATA DATA[8];
} S_PT_ROOM_REQ_INFO_SUCC_U;

typedef struct _S_PT_ROOM_REQ_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_REQ_INFO_FAIL_U;

typedef struct _S_PT_ROOM_LEAVE
{
} S_PT_ROOM_LEAVE;

typedef struct _S_PT_ROOM_LEAVE_SUCC_U
{
} S_PT_ROOM_LEAVE_SUCC_U;

typedef struct _S_PT_ROOM_LEAVE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_LEAVE_FAIL_U;

typedef struct _S_PT_ROOM_LEAVE_M
{
	DWORD_PTR SESSION_ID;
	DWORD_PTR ROOT_USER_SESSION_ID;
} S_PT_ROOM_LEAVE_M;

typedef struct _S_PT_ROOM_MAP_CHANGE
{
	DWORD MAP_INDEX;
} S_PT_ROOM_MAP_CHANGE;

typedef struct _S_PT_ROOM_MAP_SUCC_U
{
} S_PT_ROOM_MAP_SUCC_U;

typedef struct _S_PT_ROOM_MAP_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_MAP_FAIL_U;

typedef struct _S_PT_ROOM_MAP_CHANGE_M
{
	DWORD MAP_INDEX;
} S_PT_ROOM_MAP_CHANGE_M;

typedef struct _S_PT_ROOM_CHATTING
{
	WCHAR CHAT[256];
} S_PT_ROOM_CHATTING;

typedef struct _S_PT_ROOM_CHATTING_SUCC_U
{
} S_PT_ROOM_CHATTING_SUCC_U;

typedef struct _S_PT_ROOM_CHATTING_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_CHATTING_FAIL_U;

typedef struct _S_PT_ROOM_CHATTING_M
{
	DWORD_PTR SESSION_ID;
	WCHAR CHAT[256];
} S_PT_ROOM_CHATTING_M;

typedef struct _S_PT_ROOM_READY
{
	BOOL READY;
} S_PT_ROOM_READY;

typedef struct _S_PT_ROOM_READY_SUCC_U
{
} S_PT_ROOM_READY_SUCC_U;

typedef struct _S_PT_ROOM_READY_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_READY_FAIL_U;

typedef struct _S_PT_ROOM_READY_M
{
	DWORD_PTR SESSION_ID;
	BOOL READY;
} S_PT_ROOM_READY_M;

typedef struct _S_PT_ROOM_START
{
} S_PT_ROOM_START;

typedef struct _S_PT_ROOM_START_SUCC_U
{
} S_PT_ROOM_START_SUCC_U;

typedef struct _S_PT_ROOM_START_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_START_FAIL_U;

typedef struct _S_PT_ROOM_START_M
{
} S_PT_ROOM_START_M;

typedef struct _S_PT_GAME_LOAD_COMPLETE
{
} S_PT_GAME_LOAD_COMPLETE;

typedef struct _S_PT_GAME_LOAD_COMPLETE_SUCC_U
{
} S_PT_GAME_LOAD_COMPLETE_SUCC_U;

typedef struct _S_PT_GAME_LOAD_COMPLETE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_LOAD_COMPLETE_FAIL_U;

typedef struct _S_PT_GAME_LOAD_COMPLETE_M
{
	DWORD_PTR SESSION_ID;
} S_PT_GAME_LOAD_COMPLETE_M;

typedef struct _S_PT_GAME_ALL_LOAD_COMPLETE_M
{
} S_PT_GAME_ALL_LOAD_COMPLETE_M;

typedef struct _S_PT_GAME_INTRO_COMPLETE
{
} S_PT_GAME_INTRO_COMPLETE;

typedef struct _S_PT_GAME_INTRO_COMPLETE_SUCC_U
{
} S_PT_GAME_INTRO_COMPLETE_SUCC_U;

typedef struct _S_PT_GAME_INTRO_COMPLETE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_INTRO_COMPLETE_FAIL_U;

typedef struct _S_PT_GAME_INTRO_COMPLETE_M
{
	DWORD_PTR SESSION_ID;
} S_PT_GAME_INTRO_COMPLETE_M;

typedef struct _S_PT_GAME_ALL_INTRO_COMPLETE_M
{
} S_PT_GAME_ALL_INTRO_COMPLETE_M;

typedef struct _S_PT_GAME_START_M
{
} S_PT_GAME_START_M;

typedef struct _S_PT_GAME_END_M
{
} S_PT_GAME_END_M;

